/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategorySlugIndexRouteImport } from './routes/$category.$slug.index'
import { Route as AuthenticatedRecipeNewRouteImport } from './routes/_authenticated/recipe.new'
import { Route as AuthenticatedCategorySlugEditRouteImport } from './routes/_authenticated/$category.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/$category/$slug/',
  path: '/$category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipeNewRoute = AuthenticatedRecipeNewRouteImport.update({
  id: '/recipe/new',
  path: '/recipe/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategorySlugEditRoute =
  AuthenticatedCategorySlugEditRouteImport.update({
    id: '/$category/$slug/edit',
    path: '/$category/$slug/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recipe/new': typeof AuthenticatedRecipeNewRoute
  '/$category/$slug/': typeof CategorySlugIndexRoute
  '/$category/$slug/edit': typeof AuthenticatedCategorySlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recipe/new': typeof AuthenticatedRecipeNewRoute
  '/$category/$slug': typeof CategorySlugIndexRoute
  '/$category/$slug/edit': typeof AuthenticatedCategorySlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/recipe/new': typeof AuthenticatedRecipeNewRoute
  '/$category/$slug/': typeof CategorySlugIndexRoute
  '/_authenticated/$category/$slug/edit': typeof AuthenticatedCategorySlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/recipe/new'
    | '/$category/$slug/'
    | '/$category/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/recipe/new' | '/$category/$slug' | '/$category/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/recipe/new'
    | '/$category/$slug/'
    | '/_authenticated/$category/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$slug/': {
      id: '/$category/$slug/'
      path: '/$category/$slug'
      fullPath: '/$category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipe/new': {
      id: '/_authenticated/recipe/new'
      path: '/recipe/new'
      fullPath: '/recipe/new'
      preLoaderRoute: typeof AuthenticatedRecipeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$category/$slug/edit': {
      id: '/_authenticated/$category/$slug/edit'
      path: '/$category/$slug/edit'
      fullPath: '/$category/$slug/edit'
      preLoaderRoute: typeof AuthenticatedCategorySlugEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRecipeNewRoute: typeof AuthenticatedRecipeNewRoute
  AuthenticatedCategorySlugEditRoute: typeof AuthenticatedCategorySlugEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRecipeNewRoute: AuthenticatedRecipeNewRoute,
  AuthenticatedCategorySlugEditRoute: AuthenticatedCategorySlugEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
