/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RecipeSlugIndexRouteImport } from './routes/recipe.$slug.index'
import { Route as RecipeSlugFlowBRouteImport } from './routes/recipe.$slug.flow-b'
import { Route as AuthenticatedRecipeSlugEditRouteImport } from './routes/_authenticated/recipe.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugIndexRoute = RecipeSlugIndexRouteImport.update({
  id: '/recipe/$slug/',
  path: '/recipe/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugFlowBRoute = RecipeSlugFlowBRouteImport.update({
  id: '/recipe/$slug/flow-b',
  path: '/recipe/$slug/flow-b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipeSlugEditRoute =
  AuthenticatedRecipeSlugEditRouteImport.update({
    id: '/recipe/$slug/edit',
    path: '/recipe/$slug/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recipe/$slug/flow-b': typeof RecipeSlugFlowBRoute
  '/recipe/$slug/': typeof RecipeSlugIndexRoute
  '/recipe/$slug/edit': typeof AuthenticatedRecipeSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recipe/$slug/flow-b': typeof RecipeSlugFlowBRoute
  '/recipe/$slug': typeof RecipeSlugIndexRoute
  '/recipe/$slug/edit': typeof AuthenticatedRecipeSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/recipe/$slug/flow-b': typeof RecipeSlugFlowBRoute
  '/recipe/$slug/': typeof RecipeSlugIndexRoute
  '/_authenticated/recipe/$slug/edit': typeof AuthenticatedRecipeSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/recipe/$slug/flow-b'
    | '/recipe/$slug/'
    | '/recipe/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/recipe/$slug/flow-b'
    | '/recipe/$slug'
    | '/recipe/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/recipe/$slug/flow-b'
    | '/recipe/$slug/'
    | '/_authenticated/recipe/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecipeSlugFlowBRoute: typeof RecipeSlugFlowBRoute
  RecipeSlugIndexRoute: typeof RecipeSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug/': {
      id: '/recipe/$slug/'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug/'
      preLoaderRoute: typeof RecipeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug/flow-b': {
      id: '/recipe/$slug/flow-b'
      path: '/recipe/$slug/flow-b'
      fullPath: '/recipe/$slug/flow-b'
      preLoaderRoute: typeof RecipeSlugFlowBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipe/$slug/edit': {
      id: '/_authenticated/recipe/$slug/edit'
      path: '/recipe/$slug/edit'
      fullPath: '/recipe/$slug/edit'
      preLoaderRoute: typeof AuthenticatedRecipeSlugEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRecipeSlugEditRoute: typeof AuthenticatedRecipeSlugEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRecipeSlugEditRoute: AuthenticatedRecipeSlugEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RecipeSlugFlowBRoute: RecipeSlugFlowBRoute,
  RecipeSlugIndexRoute: RecipeSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
